export const ADD_ARTICLE_INIT = 'ADD_ARTICLE_INIT';

export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCES';

export const ADD_ARTICLE_FAILED = 'ADD_ARTICLE_FAILED';

export const FETCH_ARTICLES_INIT = 'FETCH_ARTICLES_INIT';

export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_INIT_SUCCESS';

export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED';